backend:
  name: git-gateway
  branch: master 
publish_mode: editorial_workflow
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  - name: sections
    label: Sections
    files:
      - label: Intros
        name: intros
        file: "data/intro.json"
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
          - label: Content
            name: content
            widget: string
          - label: Image
            name: img
            widget: image
      - label: Groups
        name: groups
        widget: list
        file: "data/groups.json"
        fields:
          - label: Name
            name: name
            widget: string
          - label: English Name
            name: name_en
            widget: string
          - label: Links
            name: links
            widget: list
            fields:
              - name: title
                label: Title
                widget: string
              - name: url
                label: Url
                widget: string
          - label: Sildes
            name: sildes
            fields:
              - name: text
                label: Text
                widget: string
              - name: img
                label: Imgage
                widget: image